### ISSUE TITLE
config for S3 Blobe Storage

### ISSUE THREAD

**Issue by Aleks3050** [AdaptiveConsulting/nexus-casc-plugin#1]
we try to use your casc plugin in our infra. All work fine but we can’t create S3 Blobe Store via casc plugin. We try to use following config(no configuration example in your README.md):
```
          - name: ibi-bucket-nexus
            type: S3
            attributes:
              s3:
                region: us-east-1
                bucket: ibi-bucket-nexus
```
But it not working, S3 Blob Storage not created and other (file storage) too.
Can you help? How can we see logs of working casc plugin and undestand what the problem?
Thank you!
