### ISSUE TITLE
Question: Proxy Authentication Configuration

### ISSUE THREAD

**Issue by kikyomits** [AdaptiveConsulting/nexus-casc-plugin#16]
Hi, can I ask you the way to set Authentication in Proxy configuration? I did take a look  in the CasC plugin source code and Nexus source code as well and tried configurations below. But didn't work. Would you please tell me if authentication configuration is supported and the example configuration if it's supported?

Thanks.

## my configuration

```yaml
repository:
  repositories:
  - name: mule-enterprise-release
    online: true
    recipeName: maven2-proxy
    attributes:
      proxy:
        contentMaxAge: -1
        remoteUrl: https://xxx.com
        metadataMaxAge: 1440
      negativeCache:
        timeToLive: 1440
        enabled: true
      storage:
        strictContentTypeValidation: true
        blobStoreName: S3
      httpClient:
        authentication:
          type: username
          username: 'aaa'
          password: 'bbb'
```
